# Generated by Django 3.1 on 2020-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_changed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='admins',
            field=models.ManyToManyField(blank=True, to='management.Admin'),
        ),
        migrations.AlterUniqueTogether(
            name='admin',
            unique_together={('first_name', 'last_name')},
        ),
    ]
