# Generated by Django 3.1 on 2020-08-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200808_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('start_time',)},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='management.Admin'),
        ),
    ]
