# Generated by Django 3.2.13 on 2022-05-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200810_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_semesters', to='management.admin')),
            ],
        ),
    ]
